# **1. Load Iris Plants Dataset**

Reference: https://www.kaggle.com/code

In [2]:
%pip install --upgrade scikit-learn==1.0.2
%pip install --upgrade numpy==1.21.5

  Using cached numpy-1.26.4-cp39-cp39-macosx_11_0_arm64.whl (14.0 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.5
    Uninstalling numpy-1.21.5:
      Successfully uninstalled numpy-1.21.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.57.1 requires numpy<1.25,>=1.21, but you have numpy 1.26.4 which is incompatible.
Note: you may need to restart the kernel to use updated packages.
  Using cached numpy-1.21.5-cp39-cp39-macosx_11_0_arm64.whl (12.4 MB)
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
scipy 1.11.1 requires numpy<1.28.0,>=1.21.6, but you

In [3]:
%pip install seaborn

Note: you may need to restart the kernel to use updated packages.


In [5]:
import time
import datetime
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# Load dataset
from sklearn.datasets import load_iris
iris = load_iris()
iris_df =  pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['target'] = iris.target
iris_df['target_names'] = [iris.target_names[t] for t in iris.target]
target_col = 'target'
feature_col = iris.feature_names

/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/scipy/__init__.py:132: UserWarning: A NumPy version >=1.21.6 and <1.28.0 is required for this version of SciPy (detected version 1.21.5)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [11]:
iris_df[:-10]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
135                7.7               3.0                6.1               2.3   
136                6.3               3.4                5.6               2.4   
137                6.4               3.1                5.5               1.8   
138                6.0               3.0                4.8               1.8   
139                6.9               3.1                5.4               2.1   

     target target_names  
0         0       setosa  
1         0       setosa  
2         0       setosa  
3         0       setosa  
4         0       setosa  
..      ...          ...  
135       2    virginica  
136       2    virginica  
137       2    virginica  
138       2    virginica  
139       2    virginica  

[140 rows x 6 columns]

In [12]:
iris_df['target_names'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: target_names, dtype: int64

<u>**Data Set Characteristics**</u>

**Number of Instances**: 150 (50 in each of three classes)  
**Number of Attributes**: 4 numeric, predictive attributes and the class  

<u>**Attribute Information**</u>
- sepal length in cm  
- sepal width in cm  
- petal length in cm  
- petal width in cm  
- class:  
  - Iris-Setosa  
  - Iris-Versicolour  
  - Iris-Virginica  

<u>**Summary Statistics**</u>

| Features | Min | Max | Mean | SD | Class Correlation |
|-:|-:|-:|-:|-:|-:|
| sepal length | 4.3 | 7.9 | 5.84 | 0.83 | 0.7826 |
| sepal width | 2.0 | 4.4 | 3.05 | 0.43 | -0.4194 |
| petal length | 1.0 | 6.9 | 3.76 | 1.76 | 0.9490 (high!) |
| petal width | 0.1 | 2.5 | 1.20 | 0.76 | 0.9565 (high!) |

**Missing Attribute Values**: None  
**Class Distribution**: 33.3% for each of 3 classes.  
**Creator**: R.A. Fisher  
**Donor**: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)  
**Date**: July, 1988  

The famous Iris database, first used by Sir R.A. Fisher. The dataset is taken
from Fisher's paper. Note that it's the same as in R, but not as in the UCI
Machine Learning Repository, which has two wrong data points.  

This is perhaps the best known database to be found in the
pattern recognition literature.  Fisher's paper is a classic in the field and
is referenced frequently to this day.  (See Duda & Hart, for example.)  The
data set contains 3 classes of 50 instances each, where each class refers to a
type of iris plant.  One class is linearly separable from the other 2; the
latter are NOT linearly separable from each other.  

**References**
- Fisher, R.A. "The use of multiple measurements in taxonomic problems"
  Annual Eugenics, 7, Part II, 179-188 (1936); also in "Contributions to
  Mathematical Statistics" (John Wiley, NY, 1950).
- Duda, R.O., & Hart, P.E. (1973) Pattern Classification and Scene Analysis.
  (Q327.D83) John Wiley & Sons.  ISBN 0-471-22361-1.  See page 218.
- Dasarathy, B.V. (1980) "Nosing Around the Neighborhood: A New System
  Structure and Classification Rule for Recognition in Partially Exposed
  Environments".  IEEE Transactions on Pattern Analysis and Machine
  Intelligence, Vol. PAMI-2, No. 1, 67-71.
- Gates, G.W. (1972) "The Reduced Nearest Neighbor Rule".  IEEE Transactions
  on Information Theory, May 1972, 431-433.
- See also: 1988 MLC Proceedings, 54-64.  Cheeseman et al"s AUTOCLASS II
  conceptual clustering system finds 3 classes in the data.
- Many, many more ...

In [13]:
from sklearn.model_selection import train_test_split

X = iris_df[feature_col]
y = iris_df[target_col]

X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.30, random_state=30)

# **2. K-Nearest Neighbors**

For Classification: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html  
For Regression: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsRegressor.html  

In [14]:
from sklearn.neighbors import KNeighborsClassifier

**Suggest Parameters**  

* **n_neighbors**: 4
* **weights**: distance

In [15]:
n_neighbors = 5 #@param {type:"slider", min:1, max:10, step:1}
weights = 'distance'  #@param ['uniform', 'distance']

knn = KNeighborsClassifier(
    n_neighbors=n_neighbors,
    weights=weights,
)

knn.fit(X_train, y_train)

KNeighborsClassifier(weights='distance')

In [16]:
# Predict as Class
train_predict = knn.predict(X_train)
test_predict = knn.predict(X_test)

# Predict as Probability
train_predict_prob = knn.predict_proba(X_train)

In [17]:
# Show first 10 prediction
print(train_predict[:10])

# Probability of 0/1
print(train_predict_prob[:10])

[0 1 1 2 2 1 2 2 2 1]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [18]:
# Actual Target
y_train[:10].tolist()

/var/folders/2_/rpnwqb4s7_3f6bmmnvl2mzj40000gn/T/ipykernel_4484/1949516819.py:2: FutureWarning: The behavior of `series[i:j]` with an integer-dtype index is deprecated. In a future version, this will be treated as *label-based* indexing, consistent with e.g. `series[i]` lookups. To retain the old behavior, use `series.iloc[i:j]`. To get the future behavior, use `series.loc[i:j]`.
  y_train[:10].tolist()


[0, 1, 1, 2, 2, 1, 2, 2, 2, 1]

In [19]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, test_predict, labels=[0, 1])

array([[15,  0],
       [ 0, 13]])

In [20]:
from sklearn.metrics import classification_report

print(classification_report(y_test, test_predict , digits=4))

              precision    recall  f1-score   support

           0     1.0000    1.0000    1.0000        15
           1     0.9286    0.8667    0.8966        15
           2     0.8750    0.9333    0.9032        15

    accuracy                         0.9333        45
   macro avg     0.9345    0.9333    0.9333        45
weighted avg     0.9345    0.9333    0.9333        45



# **3. Visualization**

Adapt from: https://scikit-learn.org/stable/auto_examples/neighbors/plot_classification.html

In [ ]:
#@markdown # **Select parameters to plot**
#@markdown **(On simplyfied model for visualization - 2 variables)**
n_neighbors = 7 #@param {type:"slider", min:1, max:10, step:1}
weights = 'distance'  #@param ['uniform', 'distance']
x_label = 'sepal length (cm)' #@param ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
y_label = 'sepal width (cm)' #@param ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

x_idx = iris_df.columns.to_list().index(x_label)
y_idx = iris_df.columns.to_list().index(y_label) 

from matplotlib import cm
from matplotlib.colors import ListedColormap
cmap_val = np.linspace(0.0, 1.0, 20)
cmap_light = ListedColormap(cm.get_cmap(plt.get_cmap('tab20'))(cmap_val)[1:7:2])
cmap_bold = ListedColormap(cm.get_cmap(plt.get_cmap('tab20'))(cmap_val)[:6:2])
h = .02  # step size in the mesh

model = KNeighborsClassifier(n_neighbors=n_neighbors, weights=weights)
model.fit(iris_df.iloc[:, [x_idx, y_idx]], iris_df[target_col])
x_min, x_max = iris_df.iloc[:, x_idx].min() - 1, iris_df.iloc[:, x_idx].max() + 1
y_min, y_max = iris_df.iloc[:, y_idx].min() - 1, iris_df.iloc[:, y_idx].max() + 1
xx, yy = np.meshgrid(
  np.arange(x_min, x_max, h),
  np.arange(y_min, y_max, h)
)
Z = model.predict(np.c_[xx.ravel(), yy.ravel()])

# Put the result into a color plot
Z = Z.reshape(xx.shape)
plt.figure(figsize=(8, 8), dpi=80)
plt.pcolormesh(xx, yy, Z, cmap=cmap_light)

# Plot also the training points
plt.scatter(
  iris_df.iloc[:, x_idx],
  iris_df.iloc[:, y_idx],
  c=iris_df[target_col],
  cmap=cmap_bold,
  edgecolor='k',
  s=60
)
plt.xlabel(x_label)
plt.xlim(xx.min(), xx.max())
plt.ylabel(y_label)
plt.ylim(yy.min(), yy.max())
plt.title("3-Class classification (k = %i, weights = '%s')"
          % (n_neighbors, weights))
plt.show()

# **4. Find the best K value**

## 4.1 Grid Search

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html

In [21]:
from sklearn.model_selection import GridSearchCV

In [22]:
grid_search = GridSearchCV(
    estimator=KNeighborsClassifier(),
    param_grid=dict(
        n_neighbors=[1,2,3,4,5,6,7,8,9,10],
        weights=['uniform', 'distance'],
    ),
    scoring='f1_weighted',
    cv=5,
    n_jobs=-1 # Parallel
)

grid_start_time = time.time()
grid_search.fit(X_train, y_train)
grid_end_time = time.time()
print(f"Searching Time: {datetime.timedelta(seconds=grid_end_time-grid_start_time)}")

/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/scipy/__init__.py:132: UserWarning: A NumPy version >=1.21.6 and <1.28.0 is required for this version of SciPy (detected version 1.21.5)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/scipy/__init__.py:132: UserWarning: A NumPy version >=1.21.6 and <1.28.0 is required for this version of SciPy (detected version 1.21.5)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/scipy/__init__.py:132: UserWarning: A NumPy version >=1.21.6 and <1.28.0 is required for this version of SciPy (detected version 1.21.5)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
/opt/homebrew/Caskroom/miniconda/base/lib/python3.9/site-packages/scipy/__init__.py:132: UserWarning: A NumPy version >=1.21.6 and <1.28.0 is required for this version o

Searching Time: 0:00:09.042424


In [23]:
# Get Searching Result
grid_search_result = grid_search.cv_results_
pd.DataFrame.from_dict(grid_search_result)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.001167      0.000258         0.002641        0.001558   
1        0.001182      0.000389         0.002300        0.001566   
2        0.001104      0.000400         0.001486        0.000045   
3        0.000972      0.000342         0.000900        0.000039   
4        0.000741      0.000060         0.001752        0.000457   
5        0.000764      0.000049         0.000917        0.000123   
6        0.000688      0.000106         0.001437        0.000079   
7        0.000890      0.000141         0.000950        0.000076   
8        0.000718      0.000078         0.001399        0.000089   
9        0.000839      0.000185         0.000914        0.000110   
10       0.000631      0.000059         0.001293        0.000062   
11       0.000904      0.000320         0.001051        0.000266   
12       0.000910      0.000339         0.001491        0.000186   
13       0.000644      0.000084         0.000824        0.000040   
14       0.000683      0.000038         0.001621        0.000326   
15       0.000716      0.000120         0.000947        0.000193   
16       0.000757      0.000032         0.001460        0.000143   
17       0.000789      0.000105         0.000951        0.000098   
18       0.000755      0.000034         0.001445        0.000110   
19       0.000874      0.000185         0.000892        0.000049   

   param_n_neighbors param_weights  \
0                  1       uniform   
1                  1      distance   
2                  2       uniform   
3                  2      distance   
4                  3       uniform   
5                  3      distance   
6                  4       uniform   
7                  4      distance   
8                  5       uniform   
9                  5      distance   
10                 6       uniform   
11                 6      distance   
12                 7       uniform   
13                 7      distance   
14                 8       uniform   
15                 8      distance   
16                 9       uniform   
17                 9      distance   
18                10       uniform   
19                10      distance   

                                        params  split0_test_score  \
0     {'n_neighbors': 1, 'weights': 'uniform'}           0.904762   
1    {'n_neighbors': 1, 'weights': 'distance'}           0.904762   
2     {'n_neighbors': 2, 'weights': 'uniform'}           0.904762   
3    {'n_neighbors': 2, 'weights': 'distance'}           0.904762   
4     {'n_neighbors': 3, 'weights': 'uniform'}           0.952137   
5    {'n_neighbors': 3, 'weights': 'distance'}           0.952137   
6     {'n_neighbors': 4, 'weights': 'uniform'}           0.904762   
7    {'n_neighbors': 4, 'weights': 'distance'}           0.904762   
8     {'n_neighbors': 5, 'weights': 'uniform'}           0.952137   
9    {'n_neighbors': 5, 'weights': 'distance'}           0.952137   
10    {'n_neighbors': 6, 'weights': 'uniform'}           0.904762   
11   {'n_neighbors': 6, 'weights': 'distance'}           0.952137   
12    {'n_neighbors': 7, 'weights': 'uniform'}           0.952137   
13   {'n_neighbors': 7, 'weights': 'distance'}           0.952137   
14    {'n_neighbors': 8, 'weights': 'uniform'}           0.904762   
15   {'n_neighbors': 8, 'weights': 'distance'}           0.952137   
16    {'n_neighbors': 9, 'weights': 'uniform'}           0.952137   
17   {'n_neighbors': 9, 'weights': 'distance'}           0.952137   
18   {'n_neighbors': 10, 'weights': 'uniform'}           0.952137   
19  {'n_neighbors': 10, 'weights': 'distance'}           0.952137   

    split1_test_score  split2_test_score  split3_test_score  \
0            1.000000                1.0           0.952137   
1            1.000000                1.0           0.952137   
2            1.000000                1.0           0.952137   
3            1.000000                1.0           0.952137   
4          

In [24]:
# Best Trained Model 
model = grid_search.best_estimator_

In [25]:
# Predict with the best model
y_pred = model.predict(X_test)
y_pred[:10]

array([2, 0, 2, 1, 2, 0, 1, 0, 2, 2])

## 4.2 Randomized Search

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.RandomizedSearchCV.html

In [27]:
from sklearn.model_selection import RandomizedSearchCV

In [28]:
rand_search = RandomizedSearchCV(
    estimator=KNeighborsClassifier(),
    param_distributions=dict(
        n_neighbors=[1,2,3,4,5,6,7,8,9,10],
        weights=['uniform', 'distance'],
    ),
    scoring='f1_weighted',
    cv=5,
    n_jobs=-1
)

rand_start_time = time.time()
rand_search.fit(X_train, y_train)
rand_end_time = time.time()
print(f"Searching Time: {datetime.timedelta(seconds=rand_end_time-rand_start_time)}")

Searching Time: 0:00:00.073502


In [29]:
# Get Searching Result
rand_search_result = rand_search.cv_results_
pd.DataFrame.from_dict(rand_search_result)

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_weights  \
0       0.003705      0.001528         0.003187        0.000347       uniform   
1       0.001446      0.000988         0.001681        0.001110      distance   
2       0.002071      0.001678         0.001257        0.000334      distance   
3       0.000783      0.000079         0.001899        0.000543       uniform   
4       0.000844      0.000371         0.000913        0.000078      distance   
5       0.001097      0.000837         0.001160        0.000589      distance   
6       0.000961      0.000619         0.001144        0.000526      distance   
7       0.000900      0.000399         0.001755        0.000393       uniform   
8       0.000816      0.000123         0.001027        0.000262      distance   
9       0.001199      0.000375         0.002239        0.000782       uniform   

  param_n_neighbors                                     params  \
0                 4   {'weights': 'uniform', 'n_neighbors': 4}   
1                 1  {'weights': 'distance', 'n_neighbors': 1}   
2                 2  {'weights': 'distance', 'n_neighbors': 2}   
3                 2   {'weights': 'uniform', 'n_neighbors': 2}   
4                 6  {'weights': 'distance', 'n_neighbors': 6}   
5                 9  {'weights': 'distance', 'n_neighbors': 9}   
6                 5  {'weights': 'distance', 'n_neighbors': 5}   
7                 5   {'weights': 'uniform', 'n_neighbors': 5}   
8                 3  {'weights': 'distance', 'n_neighbors': 3}   
9                 6   {'weights': 'uniform', 'n_neighbors': 6}   

   split0_test_score  split1_test_score  split2_test_score  split3_test_score  \
0           0.904762           1.000000                1.0           0.952137   
1           0.904762           1.000000                1.0           0.952137   
2           0.904762           1.000000                1.0           0.952137   
3           0.904762           1.000000                1.0           0.952137   
4           0.952137           1.000000                1.0           0.952137   
5           0.952137           1.000000                1.0           0.952137   
6           0.952137           1.000000                1.0           0.952137   
7           0.952137           0.952137                1.0           0.952137   
8           0.952137           1.000000                1.0           0.952137   
9           0.904762           1.000000                1.0           1.000000   

   split4_test_score  mean_test_score  std_test_score  rank_test_score  
0           0.952137         0.961807        0.035661                5  
1           0.952137         0.961807        0.035661                5  
2           0.952137         0.961807        0.035661                5  
3           0.902778         0.951935        0.043040               10  
4           0.952137         0.971282        0.023448                3  
5           1.000000         0.980855        0.023448                1  
6           0.952137         0.971282        0.023448                3  
7           0.952137         0.961709        0.019145                8  
8           1.000000         0.980855        0.023448                1  
9           0.902778         0.961508        0.047147                9

In [30]:
# Best Trained Model 
model = rand_search.best_estimator_

In [31]:
# Predict with the best model
y_pred = model.predict(X_test)
y_pred[:10]

array([2, 0, 2, 1, 2, 0, 1, 0, 2, 2])